---
- name: Build Primary CNF Switch Base
  template:
    src: roles/cisco/templates/cisco9k_pri_base.j2
    dest: roles/cisco/config_repo/{{act_hostname}}.cfg
  

#- name: Build Standby CNF Switch Base
#  template:
#    src: roles/cisco/templates/cisco9k_stb_base.j2
#    dest: roles/cisco/config_repo/{{stb_hostname}}-ansible-build-{{ansible_date_time.date}}-{{ansible_date_time.time}}.cfg

# - name: Build Standby CNF Switch Base
#   template:
#     src: roles/cisco/templates/cisco9k_pri_base.j2
#     dest: roles/cisco/config_repo/test1.cfg
