---
- name: Build Cloud Nexus Config Build Test
  hosts: localhost
  connection: local
  gather_facts: False

  vars_files:
    - ./group_vars/base_vars.yml
    - ./group_vars/cloud_vars.yml
    - ./host_vars/pri_cnf_sw.yml
    - ./host_vars/stb_cnf_sw.yml
  
  
  tasks:
    - name: Build Secondary CNF Switch
      include_role:
        name: ciscosec