---
- name: Push Cloud Nexus Config Build Test
  hosts: nxos
  connection: local
  gather_facts: False

  vars_files:
    - ./group_vars/base_vars.yml
    - ./group_vars/cloud_vars.yml
    - ./group_vars/fw_base_vars.yml
    - ./host_vars/pri_cnf_sw.yml
    - ./host_vars/stb_cnf_sw.yml
  
  tasks:
    - name: Build CNF Switches
      include_role:
        name: cisco



    - name: Push Cloud Nexus Config Build Test
      nxos_config:
        src: ./roles/cisco/config_repo/SGSGP-AR-CLS01-ansible-build-2025-04-07-11:33:19.cfg
        save_when: changed        

    
    - name: Configure Banner
      nxos_banner:
        banner: motd
        text: |
          ####################################################################
          This system is private property
          Unauthorised access is not permitted and may constitute an offence
          IF YOU ARE NOT AN AUTHORISED USER DISCONNECT IMMEDIATELY
          ####################################################################
        state: present
