---
- name: Push CNF Primary Switch Configuration
  hosts: cnfswitch2
  gather_facts: False


  vars_files:
    - ./group_vars/base_vars.yml
    - ./group_vars/cloud_vars.yml
    - ./group_vars/fw_base_vars.yml
    - ./host_vars/stb_cnf_sw.yml
    - ./group_vars/nxos.yml
  
  tasks:
    - name: Push Cloud Nexus Config Build Test
      nxos_config:
        src: ./roles/ciscosec/config_repo/{{stb_hostname}}.cfg
        save_when: changed        